// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMgM715V3TcUOkwdZ8UkqS6dSOOMiOaQ',
    appId: '1:1014789487407:web:e1c7365e86804a9a24bfda',
    messagingSenderId: '1014789487407',
    projectId: 'bitirme-a6f96',
    authDomain: 'bitirme-a6f96.firebaseapp.com',
    storageBucket: 'bitirme-a6f96.firebasestorage.app',
    measurementId: 'G-LW9L21VWX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4YclNtClGTsb0iDx_uVxs67jAQ2fZJs',
    appId: '1:1014789487407:android:b3bcbafd82da898424bfda',
    messagingSenderId: '1014789487407',
    projectId: 'bitirme-a6f96',
    storageBucket: 'bitirme-a6f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUSReHFlEfJsU3fBXvJHmXVGVPCL59zbE',
    appId: '1:1014789487407:ios:bf27787a314f94f424bfda',
    messagingSenderId: '1014789487407',
    projectId: 'bitirme-a6f96',
    storageBucket: 'bitirme-a6f96.firebasestorage.app',
    iosBundleId: 'com.example.bitirme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEMgM715V3TcUOkwdZ8UkqS6dSOOMiOaQ',
    appId: '1:1014789487407:web:f031b31723667a2324bfda',
    messagingSenderId: '1014789487407',
    projectId: 'bitirme-a6f96',
    authDomain: 'bitirme-a6f96.firebaseapp.com',
    storageBucket: 'bitirme-a6f96.firebasestorage.app',
    measurementId: 'G-ZRWWSW294D',
  );
}
